/srv/logs/postgres/postgresql.log {
    daily
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    create 0664 999 999
    sharedscripts
    postrotate
        docker kill --signal=USR1 dev-postgres >/dev/null 2>&1 || true
    endscript
}
